name: Build and deploy container app to Azure Web App - serviciosweback

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v3

    - name: Login a Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Construir y desplegar imagen Docker a Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'serviciosweback'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'Dockerfile'
        configuration-file: './Servicios Web/sistemabancario/sistemabancario/Dockerfile'
